language: c
script:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90
  - clang -coverage -O0 hello.c -o hello
  - ./hello
  - gcov hello.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
