language: c

matrix:
    include:    
      # latest compiler on OS X
      - os: osx
        osx_image: xcode10.3
        compiler: clang
        env: BUILD_CONFIGURATION=0 MACOSX_DEPLOYMENT_TARGET=10.14 WITH_COVERAGE=1
      
script:
  - clang -coverage -O0 bye.c -o bye
  - ./bye
  - gcov bye.c

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
