os: Visual Studio 2015
version: 3.99.{build}

matrix:
  fast_finish: true
  
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    configuration: Debug
    gen: "Visual Studio 16 2019"
    US_SHARED: 1
    US_THREADED: 1
    WITH_COVERAGE: 1

init:
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- cmake -version
- git config --global core.autocrlf true
  
before_build:
  - cmd: ECHO this is batch
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - cmake -version
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  - if [%WITH_COVERAGE%]==[1] set PATH=%PATH%;C:\Program Files\OpenCppCoverage
  - mkdir build & cd build
  - cmake .. -G"%gen%" -DCMAKE_BUILD_TYPE=%configuration% -DBUILD_SHARED_LIBS:BOOL=%US_SHARED% -DUS_ENABLE_THREADING_SUPPORT:BOOL=%US_THREADED% -DUS_ENABLE_COVERAGE:BOOL=%WITH_COVERAGE% -DUS_BUILD_TESTING:BOOL=1 2>&1

build_script:
  - gcc hello.c
  - gcc -o hello hello.c
  - hello

test_script:
  - cmd: ECHO it Works!!!!
